## Hi this is THE ZON those fuckers ignored my application but whatever
Okay so first we load the original CSV

In [13]:
import numpy as np
import pandas as pd

data = pd.read_parquet('data/yellow_tripdata_2026-07.parquet', engine='pyarrow')

data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,request_source
0,1,2026-07-01 00:36:25,2026-07-01 00:43:18,1.0,2.00,1.0,N,138,138,2,...,8.00,0.5,0.00,0.00,1.0,19.50,0.0,2.0,0.00,NaN
1,1,2026-07-01 00:02:53,2026-07-01 00:17:12,1.0,3.20,1.0,N,162,112,2,...,4.25,0.5,0.00,0.00,1.0,21.35,2.5,0.0,0.75,NaN
2,2,2026-07-01 00:18:56,2026-07-01 00:27:38,1.0,3.18,1.0,N,137,263,1,...,1.00,0.5,4.81,0.00,1.0,24.06,2.5,0.0,0.75,NaN
3,1,2026-07-01 00:35:06,2026-07-01 00:57:51,0.0,10.00,1.0,N,138,246,1,...,11.25,0.5,12.30,7.46,1.0,74.01,2.5,2.0,0.75,NaN
4,7,2026-07-01 00:36:59,2026-07-01 00:36:59,2.0,9.62,1.0,N,140,106,1,...,0.00,0.5,9.59,0.00,1.0,57.54,2.5,0.0,0.75,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3530104,2,2026-07-31 23:38:47,2026-07-31 23:57:28,NaN,3.77,NaN,NaN,144,255,0,...,0.00,0.5,0.00,0.00,1.0,29.95,NaN,NaN,0.75,HV0003
3530105,2,2026-07-31 23:27:38,2026-07-31 23:56:57,NaN,6.24,NaN,NaN,170,166,0,...,0.00,0.5,0.00,0.00,1.0,48.97,NaN,NaN,0.75,HV0003
3530106,2,2026-07-31 23:05:13,2026-07-31 23:22:34,NaN,2.41,NaN,NaN,249,170,0,...,0.00,0.5,0.00,0.00,1.0,23.82,NaN,NaN,0.75,HV0003
3530107,2,2026-07-31 23:45:17,2026-08-01 00:22:08,NaN,12.34,NaN,NaN,148,127,0,...,0.00,0.5,0.00,0.00,1.0,56.43,NaN,NaN,0.75,A
3530108,2,2026-07-31 23:38:55,2026-07-31 23:51:58,NaN,1.13,NaN,NaN,114,231,0,...,0.00,0.5,0.00,0.00,1.0,18.15,NaN,NaN,0.75,HV0003

### So here we found out how many columns are NaN and what is the p-value that they all just happened to have the same number of NaN

In [14]:
data.isna().sum()

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count           969727
trip_distance                  0
RatecodeID                969727
store_and_fwd_flag        969727
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge      969727
Airport_fee               969727
cbd_congestion_fee             0
request_source           2560692
dtype: int64

## Drop these bum ass DEI ass columns included

In [15]:
data.drop(columns=['store_and_fwd_flag', 'VendorID', 'extra', 'mta_tax', 'improvement_surcharge',  'congestion_surcharge', 'cbd_congestion_fee', 'tolls_amount', 'fare_amount', 'request_source', 'Airport_fee'], inplace=True)
data

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,tip_amount,total_amount
0,2026-07-01 00:36:25,2026-07-01 00:43:18,1.0,2.00,1.0,138,138,2,0.00,19.50
1,2026-07-01 00:02:53,2026-07-01 00:17:12,1.0,3.20,1.0,162,112,2,0.00,21.35
2,2026-07-01 00:18:56,2026-07-01 00:27:38,1.0,3.18,1.0,137,263,1,4.81,24.06
3,2026-07-01 00:35:06,2026-07-01 00:57:51,0.0,10.00,1.0,138,246,1,12.30,74.01
4,2026-07-01 00:36:59,2026-07-01 00:36:59,2.0,9.62,1.0,140,106,1,9.59,57.54
...,...,...,...,...,...,...,...,...,...,...
3530104,2026-07-31 23:38:47,2026-07-31 23:57:28,NaN,3.77,NaN,144,255,0,0.00,29.95
3530105,2026-07-31 23:27:38,2026-07-31 23:56:57,NaN,6.24,NaN,170,166,0,0.00,48.97
3530106,2026-07-31 23:05:13,2026-07-31 23:22:34,NaN,2.41,NaN,249,170,0,0.00,23.82
3530107,2026-07-31 23:45:17,2026-08-01 00:22:08,NaN,12.34,NaN,148,127,0,0.00,56.43
3530108,2026-07-31 23:38:55,2026-07-31 23:51:58,NaN,1.13,NaN,114,231,0,0.00,18.15

## Drop these poor people who ain't go no Amex platinum

In [16]:
data_has_tip = data[data['payment_type'] == 1].drop(columns=['payment_type'])
data_has_tip

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,tip_amount,total_amount
2,2026-07-01 00:18:56,2026-07-01 00:27:38,1.0,3.18,1.0,137,263,4.81,24.06
3,2026-07-01 00:35:06,2026-07-01 00:57:51,0.0,10.00,1.0,138,246,12.30,74.01
4,2026-07-01 00:36:59,2026-07-01 00:36:59,2.0,9.62,1.0,140,106,9.59,57.54
5,2026-07-01 00:00:37,2026-07-01 00:17:02,1.0,7.28,1.0,138,37,7.56,47.36
6,2026-07-01 00:33:53,2026-07-01 00:36:16,1.0,0.30,1.0,249,249,2.00,12.15
...,...,...,...,...,...,...,...,...,...
2560375,2026-07-31 23:19:52,2026-07-31 23:38:19,1.0,9.84,1.0,138,141,9.00,67.91
2560377,2026-07-31 23:14:43,2026-07-31 23:29:34,1.0,0.89,1.0,79,79,0.00,19.25
2560378,2026-07-31 23:47:23,2026-08-01 00:19:00,1.0,6.90,1.0,107,223,7.50,44.95
2560380,2026-07-31 23:57:13,2026-08-01 00:12:49,1.0,7.80,1.0,138,236,9.83,60.99
2560381,2026-07-31 23:15:17,2026-07-31 23:33:12,1.0,2.44,1.0,230,113,4.55,27.30

## My good friend Claude wrote this code
This cuck-coded piece of garbage turns this weird datetime format into week and holiday and whatever fatass is riding uber for 10 hours

In [17]:
from pandas.tseries.holiday import USFederalHolidayCalendar

# 1. Convert strings to datetime
data_modify = data_has_tip.copy()

data_modify["tpep_pickup_datetime"] = pd.to_datetime(data_modify["tpep_pickup_datetime"], format="%Y-%m-%d %H:%M:%S")
data_modify["tpep_dropoff_datetime"] = pd.to_datetime(data_modify["tpep_dropoff_datetime"], format="%Y-%m-%d %H:%M:%S")

# 2. Trip duration in minutes
data_modify["trip_duration_min"] = (
    data_modify["tpep_dropoff_datetime"] - data_modify["tpep_pickup_datetime"]
).dt.total_seconds() / 60

# 3. Weekday / weekend (Mon=0 ... Sun=6)
data_modify["is_weekend"] = (data_modify["tpep_pickup_datetime"].dt.dayofweek >= 5).astype(int)

# 4. Holiday / not holiday (US federal holidays)
cal = USFederalHolidayCalendar()
holidays = cal.holidays(
    start=data_modify["tpep_pickup_datetime"].min(),
    end=data_modify["tpep_pickup_datetime"].max()
)
data_modify["is_holiday"] = data_modify["tpep_pickup_datetime"].dt.normalize().isin(holidays).astype(int)

# 5. Time of day based on pickup hour
hour = data_modify["tpep_pickup_datetime"].dt.hour
data_modify["time_of_day"] = np.select(
    [
        (hour >= 5) & (hour < 12),
        (hour >= 12) & (hour < 17),
        (hour >= 17) & (hour < 21),
    ],
    ["morning", "afternoon", "evening"],
    default="night",   # 21:00–04:59
)

### Encode zone to borough

In [18]:
lookup = pd.read_csv("data/taxi_zone_lookup.csv")

id_to_value = dict(zip(lookup.iloc[:, 0], lookup.iloc[:, 1]))
id_to_value = lookup.set_index("LocationID")["Borough"].to_dict()
data_modify["pickup_borough"] = data_modify["PULocationID"].map(id_to_value)
data_modify["dropoff_borough"] = data_modify["DOLocationID"].map(id_to_value)

### Drop these illegal aliens from outside the big apple

In [19]:
data_modify.dropna()

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,tip_amount,total_amount,trip_duration_min,is_weekend,is_holiday,time_of_day,pickup_borough,dropoff_borough
2,2026-07-01 00:18:56,2026-07-01 00:27:38,1.0,3.18,1.0,137,263,4.81,24.06,8.700000,0,0,night,Manhattan,Manhattan
3,2026-07-01 00:35:06,2026-07-01 00:57:51,0.0,10.00,1.0,138,246,12.30,74.01,22.750000,0,0,night,Queens,Manhattan
4,2026-07-01 00:36:59,2026-07-01 00:36:59,2.0,9.62,1.0,140,106,9.59,57.54,0.000000,0,0,night,Manhattan,Brooklyn
5,2026-07-01 00:00:37,2026-07-01 00:17:02,1.0,7.28,1.0,138,37,7.56,47.36,16.416667,0,0,night,Queens,Brooklyn
6,2026-07-01 00:33:53,2026-07-01 00:36:16,1.0,0.30,1.0,249,249,2.00,12.15,2.383333,0,0,night,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2560375,2026-07-31 23:19:52,2026-07-31 23:38:19,1.0,9.84,1.0,138,141,9.00,67.91,18.450000,0,0,night,Queens,Manhattan
2560377,2026-07-31 23:14:43,2026-07-31 23:29:34,1.0,0.89,1.0,79,79,0.00,19.25,14.850000,0,0,night,Manhattan,Manhattan
2560378,2026-07-31 23:47:23,2026-08-01 00:19:00,1.0,6.90,1.0,107,223,7.50,44.95,31.616667,0,0,night,Manhattan,Queens
2560380,2026-07-31 23:57:13,2026-08-01 00:12:49,1.0,7.80,1.0,138,236,9.83,60.99,15.600000,0,0,night,Queens,Manhattan
2560381,2026-07-31 23:15:17,2026-07-31 23:33:12,1.0,2.44,1.0,230,113,4.55,27.30,17.916667,0,0,night,Manhattan,Manhattan

### Remove even more bum ass DEI columns

In [20]:
data_modify = data_modify.drop(columns=['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'PULocationID', 'DOLocationID'])

### Remove nonsensical data from trolls that can't even operate a fucking timer

In [21]:
data_modify = data_modify[(data_modify["tip_amount"] >= 0) & (data_modify["total_amount"] >= 0) & (data_modify['trip_distance'] > 0) & (data_modify['trip_duration_min'] > 1)]

### I got cold so I made me a parka

In [22]:
data_modify.to_parquet('data/taxi_data.parquet')

### Sampling our fat ass data to make it actually fit fucking obese ass dataset

In [23]:
sampled_data = data_modify.sample(frac=0.05, random_state=1)
sampled_data.describe()

,passenger_count,trip_distance,RatecodeID,tip_amount,total_amount,trip_duration_min,is_weekend,is_holiday
count,105855.00000,105855.000000,105855.000000,105855.000000,105855.000000,105855.000000,105855.000000,105855.000000
mean,1.25158,3.281348,3.453309,4.351515,30.039123,16.839245,0.220925,0.023079
std,0.65132,4.397505,15.080419,4.205111,23.242086,25.972417,0.414872,0.150154
min,0.00000,0.010000,1.000000,0.000000,5.820000,1.016667,0.000000,0.000000
25%,1.00000,1.010000,1.000000,2.110000,17.200000,7.966667,0.000000,0.000000
50%,1.00000,1.700000,1.000000,3.370000,22.350000,13.033333,0.000000,0.000000
75%,1.00000,3.220000,1.000000,5.000000,31.920000,20.916667,0.000000,0.000000
max,6.00000,170.000000,99.000000,125.450000,627.200000,1436.800000,1.000000,1.000000

In [24]:
sampled_data.to_csv('data/truncated_data.csv')